### PR TITLE
added support for mapping properties ...

### LINKED ISSUE #53: Support "mapping property" / "mapping template" in value field
```
 {{{field|P2Protocols3|input type=SF_Select|query=((Category:Protocol))((Protocol Belongs to Project::@@@@));?Has Name;format~list;sep~,;link~none;headers~hide;limit~
200|sametemplate|field=Project1|label}}}
```

...will fail, if field _Project1_ uses _mapping property_ or _mapping template_ (e.g. to support Display Title).

Any ideas / suggestions?

### PR DESCRIPTION
**Pull request by gesinn-it**
... for combobox and tokens input types. This fixes #53. Minor code formatting.

### CODE REVIEW

**Comment by gesinn-it** [comment]
I discovered, that there is still an issue with re-populating the Select field on form edit. Bug hunting...

**Comment by gesinn-it** [comment]
fixed all issues

**Comment by gesinn-it** [comment]
@toniher @mwjames can you please have a look at this PR. Would be great to get it merged so I can start working on #62 without interference.

I did the following tests in my box:

**Tokens without 'value-initial':**
[ok] without mapping, new page
[ok] without mapping, edit page
[n/a] with mapping, new page
[n/a] with mapping, edit page

**Combobox without 'value-initial':**
[ok] without mapping, new page
[ok] without mapping, edit page
[n/a] with mapping, new page
[n/a] with mapping, edit page

**Tokens with 'value-initial':**
[ok] without mapping, new page
[ok] without mapping, edit page
[ok] with mapping, new page
[ok] with mapping, edit page

**Combobox with 'value-initial':**
[ok] without mapping, new page
[ok] without mapping, edit page
[ok] with mapping, new page
[ok] with mapping, edit page

**Comment by mwjames** [comment]
> can you please have a look at this PR. Would be great to get it merged so I can start 

The JS code becomes scarier with every iteration. I cannot vouch for its functionality but of course I can merge it under premise that it has been tested and doesn't break anything else.

PS: The JS needs some serious refactoring (a follow-up would be highly appreciated) at least break the stuff into prototype methods otherwise this just becomes an unmaintainable piece of ....

**Comment by gesinn-it** [comment]
@mwjames I just recently started working with SFS and I completely agree what you're saying. Needs some refactoring as follow-up.

@jaideraf @DengroWikibase : can you please test this PR and give us some feedback if it's not breaking things in your setups?

**Comment by jaideraf** [comment]
@gesinn-it It is not working to me. Although I am not sure if what is going here is really what I need. I will try to explain: 
I have set `$wgPageFormsUseDisplayTitle = true;`
I have the following code in the form: 

Field 1: `{{{field|Has holding institution|input type=combobox|values from category=Institution}}}` (working fine)

Field 2: `{{{field|Has location|input type=SF_Select|query=((Display title of::@@@@));?-Is located in;format~list;sep~,;link~none;headers~hide;mainlabel~-|sametemplate|field=Has holding institution}}` (not working as intended: not showing the _Display title of_ data)

OR even if I include `mapping property=Display title of` as in:

Field 2: `{{{field|Has location|input type=SF_Select|query=((Display title of::@@@@));?-Is located in;format~list;sep~,;link~none;headers~hide;mainlabel~-|sametemplate|field=Has holding institution|mapping property=Display title of}}}` (again not working as intended: not showing the _Display title of_ data)

[See the result](https://www.dropbox.com/s/n11fnpeau835fme/field_localizacao_not_showing_display_title_of.png?dl=0).

That's why my comment here https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/53:

> I also need a mapping property to show the values of _Display title of_ in a SFS field.

I need to change my form code above to get it work? Is `value-initial` a new parameter to users? Or is just something developers should care about? 
Thanks for caring.

**Comment by gesinn-it** [comment]
@jaideraf it should work as before (without mapping), not crashing etc.

To support mapping, we need some changes in Page Forms. I'm currently working with @yaronkoren on this.

**Comment by mwjames** [comment]
I'm on my weekend sprint which means a merge window.

Above comments did not clarify whether this change is an improvement or brings a regression therefore a clear indication of +1 or -1 would be much appreciated.

**Comment by gesinn-it** [comment]
@mwjames I continued working this week on #62 which is related to this issue. #62 was required due to some improvements @yaronkoren wanted to make to PF. #62 will be a major refactoring of SFS extension. If you don't mind, I would wait for #62 to avoid unnecessary effort.

**Comment by mwjames** [comment]
> If you don't mind, I would wait for #62 to avoid unnecessary effort.

I don't mind, I just wanted to check-in to see if something is required for me to act on.

**Comment by gesinn-it** [comment]
I will remove this PR to avoid mass notifications during dev. Will make a new PR as soon as dev is done.

**Pull request closed without merging**
