### PR TITLE
Make 2.1.1 release

### PR DESCRIPTION
**Pull request by kghbln**

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames @JeroenDeDauw This is to help users install correct versions as well as fixing my error not incrementing the version for the last release. Could you pls check that there is not issue with it. Should we care about HHVM?

**Comment by mwjames** [comment]
> Could you pls check that there is not issue with it. Should we care about
> HHVM?

If you add `dist: trusty` (see SMW-core) or maintain `allow_failures`
to the .travis.yml then HHVM should work again.

**Comment by kghbln** [comment]
> If you add `dist: trusty` (see SMW-core) or maintain `allow_failures` to the .travis.yml then HHVM should work again.

Keeping fingers crossed. Done with https://github.com/SemanticMediaWiki/SemanticFormsSelect/commit/37fa8016b4f82b36925f101854b72d4a53a46069#diff-354f30a63fb0907d4ad57269548329e3

In general you think that it is ok what I am trying to do with this release?

**Comment by mwjames** [comment]
> In general you think that it is ok what I am trying to do with this
> release?

What should I say, if PF cannot keep semver compliance then there is
other choice to restrict the dependency on the matter of not breaking
the extension.

Cheers

**Comment by kghbln** [comment]
Oh man, this thing is using extension.json so this is messed up again, just the other way around. Whatever, that's just the way it is now.

**Comment by kghbln** [comment]
Just created a release template: https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/69 to avoid this once and for all.

**Comment by mwjames** [comment]
> Oh man, this thing is using extension.json so this is messed up again, just
> the other way around. Whatever, that's just the way it is now.

@legoktm Any chances we could get [0] back-ported to 1.27/1.28 to
avoid us having to maintain different locations of (as in this case)
the version number?

[0] https://phabricator.wikimedia.org/T151136

**Comment by legoktm** [comment]
I submitted backports for 1.27 and 1.28 and they were just approved and will be in the next release.

**Comment by kghbln** [comment]
@legoktm Thanks a ton.

**Pull request merged**
