### PR TITLE
Update SemanticForms to 3.5

### PR DESCRIPTION
**Pull request by paladox**
This release fixes a lot of problems including through composer.

It fixes the problem we were having with composer.

@mwjames and @JeroenDeDauw please merge.

I will do a follow up that fixes it where it says something about undefined index SF_VERSION.

### CODE REVIEW

**Comment by mwjames** [comment]
> It fixes the problem we were having with composer.

[0] did not acknowledge nor mentioned that the previous SF release broke other extensions and I'd like to avoid a situation where @kghbln again sits in tears [1] just because some people don't understand what it means to operate in a semver environment.

I'd be delighted to merge under the condition that it doesn't break our sandbox again.

[0] http://wikimedia.7.x6.nabble.com/SF-Version-3-5-quot-datepicker-quot-and-quot-regexp-quot-input-types-added-etc-td5060293.html

[1] https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/5#issue-126055782

**Comment by paladox** [comment]
Sorry that it broke it for you, just needs minor adjustment and it should start working.

**Comment by JeroenDeDauw** [comment]
This is weird. Before it stated it did not work with 3.5 or above, and now it states it only works with 3.5 or above, without any other changes having been made.

**Comment by paladox** [comment]
Well that's because semanticforms 3.4.2 or 3.4.1 were not working correctly. It should all be working now as long as we make minor changes.

**Comment by paladox** [comment]
Oh I see you want it to work In 2.8 but how do we do that and ignore the 3.4.1 and 3.4.2 releases and allow 3.5 or higher/

**Comment by mwjames** [comment]
Modifications have been consolidated in #30.

**Pull request closed without merging**
