### PR TITLE
1.3.0 release

### PR DESCRIPTION
**Pull request by mwjames**

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln @toniher How about putting a lid on this?

**Comment by JeroenDeDauw** [comment]
:+1:

**Comment by kghbln** [comment]
:+1:

@toniher Wanna throw in a thumb up?

**Comment by toniher** [comment]
:+1:
Thanks a lot @mwjames !

**Comment by JeroenDeDauw** [comment]
Still needs a 1.3.0 tag. Shall I go ahead and create one?

**Comment by kghbln** [comment]
I accidently has a 1.3 tag. Can this be changed?

**Comment by JeroenDeDauw** [comment]
1.3 is also fine, though not quite as fluffy

**Comment by kghbln** [comment]
:+1:

**Comment by JeroenDeDauw** [comment]
@toniher looks like the packagist package has not been refreshed yet, meaning the GH hook here is not set up. I can do that, though then I need access to the package. Can you add these users as admins to it?

https://packagist.org/users/SMW/
https://packagist.org/users/Jeroen%20De%20Dauw/

**Comment by toniher** [comment]
I added 1.3 tag. Next time I will add 0. @JeroenDeDauw I already updated and added you into packagist.

**Comment by kghbln** [comment]
No worries. This tag is better than no tag. Most people forget about tags entirely. So... :) I also just found out last week that semver requires the complete version mapping. 1.3 would be something for marketing or so.

**Comment by JeroenDeDauw** [comment]
@kghbln the thing is, if you use Composer, the tags kinda are important :) No tag means the version does not exist essentially. Luckily Composer does not care if you put `1.3.0`, `1.3` or `v1.3.0.0`.

**Comment by kghbln** [comment]
This is an additional valid point though without the immediate necessity to tag in a particular way. Just done the release tweet.

**Pull request merged**
