### PR TITLE
Add extension.json

### PR DESCRIPTION
**Pull request by mwjames**
wfLoadExtension( 'SemanticFormsSelect' );

### CODE REVIEW

**Comment by mwjames** [comment]
```
Semantic Forms Select: 2.0.0-alpha
Semantic MediaWiki: 2.4.0-rc1 (SMWSQLStore3, sqlite)
MediaWiki:          1.27.0-rc.1 (MediaWiki vendor autoloader)
Site language:      en
Execution time:     2016-06-22 06:08
Xdebug:             2.2.7 (enabled)
PHPUnit 3.7.38 by Sebastian Bergmann.
Configuration read from /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticFormsSelect/phpunit.xml.dist
.........
Time: 343 ms, Memory: 37.75MB
```

I would only agree on a merge after [0] have been resolved and is back-ported.

[0] "...to specify several requirements for the extension, such as a specific MediaWiki version (or greater/less than) or another extension (not implemented yet ..." https://www.mediawiki.org/wiki/Manual:Extension_registration#Requirements_.28Dependencies.29

PS: `InvalidArgumentException: The value for 'load_composer_autoloader' should be an array in ` hence this requires 1.27+.

**Comment by paladox** [comment]
@mwjames I filled https://phabricator.wikimedia.org/T138370

**Comment by mwjames** [comment]
@paladox I'd like to see that the `ExtensionRegistry` callback has access to the credits information.

```php
		foreach ( $info['callbacks'] as $cb ) {
			call_user_func_array( $cb, array( $info['credits'] ) );
		}
```
```php
	public static function initExtension( $credits ) {

		define(
			'SFS_VERSION',
			isset( $credits['Semantic Forms Select']['version'] ) ? $credits['Semantic Forms Select']['version'] : true
		);
```

to avoid introducing a dependency on `ExtensionRegistry` like:

```php
	public static function getVersion() {
		$extensionData = ExtensionRegistry::getInstance()->getAllThings();

		if ( isset( $extensionData['Semantic Forms Select'] ) ) {
			return $extensionData['Semantic Forms Select']['version'];
		}

		return null;
	}
```

**Comment by mwjames** [comment]
@Seb35 Maybe something you want to test or play with?

**Comment by Seb35** [comment]
Ok, I played with :) Works fine for me on the SFS side with this patch on MW 1.27.1, 1.28.0-rc.1, 1.29.0-alpha/master. Tests successfully executed locally for me (on 1.28 and 1.29, not 1.27 because there is no UnitTestsList hook, but it’s not important).
(I had issues with SF 3.7 on MW 1.27 and 1.28 because its extension.json is v2 and these MW versions don’t recognise this, but that’s out of scope here.)

I added some instructions in the README to activate the extension, in the pull request.

Thanks for your work on this.

**Comment by Seb35** [comment]
I wanted to submit the pull request in this pull request, but I guess it’s not possible, so #36 is an improvement of this pull request.

**Comment by kghbln** [comment]
> (I had issues with SF 3.7 on MW 1.27 and 1.28 because its extension.json is v2 and these MW versions don’t recognise this, but that’s out of scope here.)

Indeed, manifest 2 should haver have been in this SF release and this was rectified with PF 4. I think manifest is scary since it introduces a breaking change with otherwise unchanged and working code. I currently do no understand the magic.

**Comment by mwjames** [comment]
> because its extension.json is v2 and these MW versions don’t recognise this, but that’s out of scope here.)

One reason I cannot get warm with `extension.json` is because of its inconsistency. (Another reason is that registration of an extension is delayed until after the LocalSettings.php which doesn't really matter here but it becomes a real problem in SMW when you need to defined NS constants etc.)

> Indeed, manifest 2 should haver have been in this SF release and this was rectified with PF 4.

If someone feels up for the task of replacing SF with PageForms can hopefully resolve the situation (and allows the tests to pass again). Given that I know null to nothing about PF and/or its changes, adapting [0, 1] maybe enough to make it work and would inherently satisfy a 2.0 release.

[0] https://github.com/SemanticMediaWiki/SemanticFormsSelect/blob/master/SemanticFormsSelect.php#L70-L76
[1] https://github.com/SemanticMediaWiki/SemanticFormsSelect/blob/master/composer.json#L27

**Comment by kghbln** [comment]
> If someone feels up for the task of replacing SF with PageForms can hopefully resolve the situation (and allows the tests to pass again)

@paladox is just having a go at it with https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/38 Great!

**Comment by paladox** [comment]
Needs rebase.

**Comment by mwjames** [comment]
> Tests successfully executed locally for me (on 1.28 and 1.29, not 1.27 because there is no UnitTestsList hook, but it’s not important).

We don't rely on `UnitTestsList`, just run `composer phpunit` from the extension base directory (you could also run `phpunit` but then you have to find the path yourself).

@Seb35 Would be nice if you could help @kghbln prepare a release by testing the current master and if something is missing to post a PR (I'll be out for a week, so no merges from my side!)

Mind the changed environment PHP 5.5/MW 1.27 as requirement.

**Pull request merged**
