### PR TITLE
Fixing issue when multiple sf_select with the same parameter in the same page

### PR DESCRIPTION
**Pull request by toniher**
I noticed it in my own deployment. A fix below.

### CODE REVIEW

**Comment by toniher** [comment]
Thanks @mwjames, I merged it myself in the end.

**Comment by kghbln** [comment]
@toniher This version is up and running at sandbox. Happy testing. If you have positive feedback on this and Alexander's change we could do a 2.1.0 release.

**Comment by mwjames** [comment]
[0] shows:
```
Exception in module-execute in module ext.sf_select.scriptselect: load.php:176:524
ReferenceError: assignment to undeclared variable valuepat ReferenceError: assignment to undeclared variable valuepat
Stack trace:
@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=ext.echo.api%2Cinit%7Cext.headertabs%2Cpageforms%7Cext.pageforms.autogrow%2Cbrowser%2Ccheckboxes%2Cdynatree%2Cfancybox%2Cimagepreview%2Cmain%2Crating%2Cselect2%2Csubmit%7Cext.sf_select.scriptselect%7Cext.summary.cards%7Cext.summary.cards.tooltip%7Cext.uls.geoclient%2Cinit%7Cjquery.checkboxShiftClick%2CgetAttrs%2ChighlightText%2CmakeCollapsible%2Cmw-jump%2Cplaceholder%2Csuggestions%7Cmediawiki.ForeignApi%2CUri%2CsearchSuggest%2Ctemplate%7Cmediawiki.ForeignApi.core%7Cmediawiki.api.parse%7Cmediawiki.page.ready%7Cmediawiki.template.regexp%7Conoi.blobstore%2ClocalForage%2Cmd5%2Cutil%7Coojs%2Csite&skin=vector&version=1gvvrz2:265:161
@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=ext.echo.api%2Cinit%7Cext.headertabs%2Cpageforms%7Cext.pageforms.autogrow%2Cbrowser%2Ccheckboxes%2Cdynatree%2Cfancybox%2Cimagepreview%2Cmain%2Crating%2Cselect2%2Csubmit%7Cext.sf_select.scriptselect%7Cext.summary.cards%7Cext.summary.cards.tooltip%7Cext.uls.geoclient%2Cinit%7Cjquery.checkboxShiftClick%2CgetAttrs%2ChighlightText%2CmakeCollapsible%2Cmw-jump%2Cplaceholder%2Csuggestions%7Cmediawiki.ForeignApi%2CUri%2CsearchSuggest%2Ctemplate%7Cmediawiki.ForeignApi.core%7Cmediawiki.api.parse%7Cmediawiki.page.ready%7Cmediawiki.template.regexp%7Conoi.blobstore%2ClocalForage%2Cmd5%2Cutil%7Coojs%2Csite&skin=vector&version=1gvvrz2:263:1
execute/runScript/<@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:161:722
jQuery.Callbacks/fire@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:45:104
jQuery.Callbacks/self.add@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:45:656
.Deferred/promise.always@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:46:865
execute/runScript@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:161:588
execute/</checkCssHandles@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:162:315
execute@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:163:25
handlePending@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:158:599
execute/runScript/markModuleReady@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:161:164
execute/runScript/<@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:161:776
jQuery.Callbacks/fire@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:45:104
jQuery.Callbacks/self.add@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:45:656
.Deferred/promise.always@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:46:865
execute/runScript@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:161:588
execute/</checkCssHandles@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:162:315
execute/</cssHandle/<@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:162:445
jQuery.Callbacks/fire@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:45:104
jQuery.Callbacks/self.fireWith@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:46:431
jQuery.Callbacks/self.fire@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:46:474
fireCallbacks@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:156:578
addEmbeddedCSS@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:157:176
addEmbeddedCSS/cssBufferTimer<@https://sandbox.semantic-mediawiki.org/w/load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=1hnjvsg:156:796
 load.php:176:562
```

[0] https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:AjouterDonn%C3%A9es/DemoAjax1

**Comment by kghbln** [comment]
@toniher @mwjames Are we ready for a 2.1.0 release?

**Comment by toniher** [comment]
I think it's worth it!

**Comment by kghbln** [comment]
> I think it's worth it!

https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/57 :)

**Pull request merged**
