### PR TITLE
Test

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by mwjames** [comment]
Still has the SF reference [0].

[0] https://packagist.org/packages/mediawiki/semantic-forms-select#dev-master

**Comment by paladox** [comment]
@mwjames yep until someone updates packagist.

**Comment by mwjames** [comment]
@JeroenDeDauw Any idea why the `@dev` reference [0] is still from 12 Nov. in packagist?

[0] https://packagist.org/packages/mediawiki/semantic-forms-select#dev-master

**Comment by mwjames** [comment]
@JeroenDeDauw I'd appreciate if you could update packagist (I can't) because the ref is still on ` 2016-11-12 13:12 UTC`.

**Comment by mwjames** [comment]
@paladox @kghbln Tests went green today, so anyone hungry for a 2.0 release?

**Comment by paladox** [comment]
Oh thankyou

**Comment by kghbln** [comment]
I'd like to get in https://github.com/SemanticMediaWiki/SemanticFormsSelect/pull/37 before. However making a 2.0 releases does make very much sense.

**Comment by kghbln** [comment]
I have just installed master of SFS together with master of PF on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Version) and the wiki is not down on its knees - which is good.

**Comment by kghbln** [comment]
I have created https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/44 to track the release.

**Comment by kghbln** [comment]
This pull and all consecutive ones do not make it to the world. Something is still broken. :(

**Pull request merged**
